/**
 * GENERATED by scripts/generate-slot-fields.mjs — the fields each section
 * slot actually uses. The Studio hides the other (empty) fields of a section
 * so editors only see what the website renders.
 *
 * To expose a field for a slot, add its name here (or re-run the generator
 * after the field has content).
 */

export type SlotFieldLevels = {
  /** Fields on the section itself. */
  section: string[];
  /** Fields inside the section heading. */
  heading: string[];
  /** Fields on each card. */
  card: string[];
  /** Fields on entries nested inside cards. */
  cardEntry: string[];
  /** Fields on entries directly on the section. */
  entry: string[];
};

/** Keyed by "<page id>/<slot>". */
export const SLOT_FIELDS: Record<string, SlotFieldLevels> = {
  "site-about-page/accreditations": {
    "section": [
      "body",
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/boardGovernors": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "image",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/branches": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "label",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/governance": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/inspection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/intro": {
    "section": [
      "body",
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/khdaSection": {
    "section": [
      "ctas",
      "heading",
      "icon",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/principalMessage": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/statement": {
    "section": [
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-about-page/values": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "entries",
      "image",
      "title"
    ],
    "cardEntry": [
      "icon",
      "label",
      "text"
    ],
    "entry": []
  },
  "site-academics-elementary-page/assessmentSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-elementary-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-elementary-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/apBenefitsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/apCoursesSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/apDiplomaSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/careerGuidanceSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/excellenceSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/overviewSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/pathwaysSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-high-school-page/pathwaysSliderSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-kindergarten-page/assessmentSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-kindergarten-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-kindergarten-page/excellenceSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-kindergarten-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/assessmentSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/curriculumOverviewSection": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/curriculumOverviewSection.firstBlock": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/curriculumOverviewSection.secondBlock": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/learningPhasesElementaryImage": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/overviewSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/supportProgramsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-middle-school-page/tailoredInstructionSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-page/curriculumOverviewSection.firstBlock": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-page/curriculumOverviewSection.secondBlock": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-page/curriculumSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-page/learningSliderSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-academics-page/skillsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "entries",
      "title"
    ],
    "cardEntry": [
      "icon",
      "iconType",
      "label"
    ],
    "entry": []
  },
  "site-academics-page/teachingCommitmentsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-application-page/applicationProcess": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-application-page/finalCta": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-application-page/mograHubAppBand": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "iconType",
      "label",
      "text"
    ]
  },
  "site-admissions-application-page/stepsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "label",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-application-page/timelinesSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-book-tour-page/formSection": {
    "section": [
      "errorMessage",
      "recipientEmail",
      "submitLabel",
      "successMessage"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-book-tour-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-faq-page/faqSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-faq-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-fees-page/discountPolicy": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-fees-page/feesIntro": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-fees-page/feeStructure": {
    "section": [
      "cards",
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "entries",
      "title"
    ],
    "cardEntry": [
      "label",
      "text"
    ],
    "entry": [
      "label",
      "text"
    ]
  },
  "site-admissions-fees-page/termsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "body",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-fees-page/termsSection.rightColumn": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "body",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-page/policySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-admissions-withdrawal-page/intro": {
    "section": [
      "body",
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-careers-page/careSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-careers-page/editorialSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-careers-page/intro": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-careers-page/joinTeamSection": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "icon",
      "label",
      "text"
    ]
  },
  "site-careers-page/requirementsSection": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "description",
      "entries",
      "title"
    ],
    "cardEntry": [
      "text"
    ],
    "entry": []
  },
  "site-contact-page/contactInfo": {
    "section": [
      "entries",
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "href",
      "iconType",
      "label",
      "text"
    ]
  },
  "site-extra-curricular-activities-page/activitiesSection": {
    "section": [
      "ctas",
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-extra-curricular-activities-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-food-services-nutrition-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-health-safety-page/approachSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-health-safety-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/accreditations": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/ctaBand": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/facts": {
    "section": [
      "entries",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": [
      "label",
      "text"
    ]
  },
  "site-homepage-main/heroContactBand": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/instagram": {
    "section": [
      "ctas",
      "heading",
      "images"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/intro": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/learningPhases": {
    "section": [
      "cards",
      "cta",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/news": {
    "section": [
      "cta",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/quickLinks": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/tour": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "accentTitle",
      "description",
      "subtitle",
      "title"
    ],
    "card": [
      "cta",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/whyDubai": {
    "section": [
      "cards",
      "heading",
      "image"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-homepage-main/whySection": {
    "section": [
      "ctas",
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-medical-services-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-news-listing-page/newsListing": {
    "section": [
      "cta",
      "heading"
    ],
    "heading": [
      "subtitle",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-our-campus-page/facilities": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "body",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-our-campus-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-our-campus-page/videoSection": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-our-community-page/linksSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "cta",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-our-community-page/supportSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-our-team-page/administrationSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-our-team-page/departmentsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "entries",
      "image",
      "title"
    ],
    "cardEntry": [
      "icon",
      "label"
    ],
    "entry": []
  },
  "site-our-team-page/leadershipSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "eyebrow",
      "title"
    ],
    "card": [
      "description",
      "image",
      "label",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-our-team-page/pastoralSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-parent-involvement-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-parent-involvement-page/proactiveApproach": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-parent-involvement-page/videoHeading": {
    "section": [
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-parent-involvement-page/videoSection": {
    "section": [
      "image"
    ],
    "heading": [],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-school-calendar-page/calendarDownload": {
    "section": [
      "ctas",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-school-calendar-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-school-calendar-page/terms": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "entries",
      "title"
    ],
    "cardEntry": [
      "label",
      "text"
    ],
    "entry": []
  },
  "site-school-policies-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-school-policies-page/policies": {
    "section": [
      "cards"
    ],
    "heading": [],
    "card": [
      "image",
      "label",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-school-supplies-uniform-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-school-supplies-uniform-page/uniformSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-inclusion-page/approachSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-inclusion-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-inclusion-page/supportProgramsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "icon",
      "iconType",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-life-page/intro": {
    "section": [
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-life-page/learningSliderSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "description",
      "image",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/coreValuesSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/eligibilitySection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/introSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/leadershipStructureSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "eyebrow",
      "title"
    ],
    "card": [
      "description",
      "image",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/leadershipStructureSection.ministerialMembers": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "title"
    ],
    "card": [
      "image",
      "subtitle",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/proactiveApproach": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/sgaGoalsSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-programs-page/studentCongressSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-staff-wellbeing-page/commitment": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-staff-wellbeing-page/counsellingSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-staff-wellbeing-page/proactiveApproach": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "description",
      "icon"
    ],
    "cardEntry": [],
    "entry": []
  },
  "site-student-staff-wellbeing-page/selSection": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-student-staff-wellbeing-page/wellbeingFramework": {
    "section": [
      "heading",
      "image"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [],
    "cardEntry": [],
    "entry": []
  },
  "site-transportation-safety-page/guidelinesSection": {
    "section": [
      "cards",
      "heading"
    ],
    "heading": [
      "description",
      "title"
    ],
    "card": [
      "description",
      "icon",
      "title"
    ],
    "cardEntry": [],
    "entry": []
  }
};

/** Hero fields used per page id. */
export const HERO_FIELDS: Record<string, { hero: string[]; heading: string[] }> = {
  "site-about-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "site-academics-elementary-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-academics-high-school-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "site-academics-kindergarten-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-academics-middle-school-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "eyebrow",
      "title"
    ]
  },
  "site-academics-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-application-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-book-tour-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-faq-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-fees-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-admissions-withdrawal-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-careers-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-contact-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-extra-curricular-activities-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-food-services-nutrition-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-health-safety-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-homepage-main": {
    "hero": [
      "heading",
      "image"
    ],
    "heading": [
      "subtitle",
      "title"
    ]
  },
  "site-medical-services-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-news-listing-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-our-campus-page": {
    "hero": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ]
  },
  "site-our-community-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-our-team-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-parent-involvement-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-school-calendar-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-school-policies-page": {
    "hero": [
      "heading",
      "image"
    ],
    "heading": [
      "title"
    ]
  },
  "site-school-supplies-uniform-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-student-inclusion-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-student-life-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-student-programs-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-student-staff-wellbeing-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  },
  "site-transportation-safety-page": {
    "hero": [
      "heading",
      "image",
      "mobileImage"
    ],
    "heading": [
      "title"
    ]
  }
};
